ALTER TABLE `dict_types`
  MODIFY `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  MODIFY `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `dict_data`
  MODIFY `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  MODIFY `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

INSERT INTO `dict_types` (`dict_name`, `dict_type`, `status`, `remark`)
VALUES
  ('资源技能标签', 'RESOURCE_SKILL_TAGS', 'normal', NULL),
  ('资源地区标签', 'RESOURCE_REGION_CODES', 'normal', NULL),
  ('资源大厅城市节点', 'RESOURCE_CITY_NODES', 'normal', NULL),
  ('资源目标心愿标签', 'RESOURCE_WISH_TAGS', 'normal', NULL),
  ('资源业务需求标签', 'RESOURCE_NEED_TAGS', 'normal', NULL)
ON DUPLICATE KEY UPDATE
  `dict_name` = VALUES(`dict_name`),
  `status` = VALUES(`status`),
  `remark` = VALUES(`remark`);

INSERT INTO `dict_data` (`dict_type`, `dict_code`, `dict_label`, `dict_value`, `dict_sort`, `status`, `remark`)
VALUES
  ('RESOURCE_SKILL_TAGS', 'short_video', '短视频', '短视频', 1, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'short_video_script', '短视频脚本', '短视频脚本', 2, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'short_video_shooting', '短视频拍摄', '短视频拍摄', 3, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'video_editing', '视频剪辑', '视频剪辑', 4, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'live_stream', '直播', '直播', 5, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'live_stream_ops', '直播运营', '直播运营', 6, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'anchor_training', '主播培训', '主播培训', 7, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'account_ops', '账号代运营', '账号代运营', 8, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'content_copywriting', '内容文案', '内容文案', 9, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'brand_copywriting', '文案策划', '文案策划', 10, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'event_execution', '活动执行', '活动执行', 11, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'corporate_live', '企业自播', '企业自播', 12, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'ip_incubation', 'IP孵化', 'IP孵化', 13, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'private_domain_ops', '私域运营', '私域运营', 14, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'community_ops', '社群运营', '社群运营', 15, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'seo_sem', 'SEO/SEM', 'SEO/SEM', 16, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'ecommerce_ops', '电商运营', '电商运营', 17, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'shop_ops', '店铺运营', '店铺运营', 18, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'local_life_ops', '本地生活运营', '本地生活运营', 19, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'ai_tools', 'AI工具应用', 'AI工具应用', 20, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'ai_editing', 'AI剪辑', 'AI剪辑', 21, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'graphic_design', '平面设计', '平面设计', 22, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'brand_strategy', '品牌策划', '品牌策划', 23, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'creator_bd', '达人对接', '达人对接', 24, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'influencer_bd', '博主商务', '博主商务', 25, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'visit_store_shoot', '探店拍摄', '探店拍摄', 26, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'photography', '摄影摄像', '摄影摄像', 27, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'product_selection', '选品', '选品', 28, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'data_analysis', '数据分析', '数据分析', 29, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'customer_service', '客服转化', '客服转化', 30, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'supply_chain', '供应链对接', '供应链对接', 31, 'normal', NULL),
  ('RESOURCE_SKILL_TAGS', 'training_coach', '培训教练', '培训教练', 32, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '000000', '全国', '全国', 1, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '110000', '北京', '北京', 2, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '310000', '上海', '上海', 3, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '440100', '广州', '广州', 4, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '440300', '深圳', '深圳', 5, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '330100', '杭州', '杭州', 6, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '510100', '成都', '成都', 7, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '420100', '武汉', '武汉', 8, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '320100', '南京', '南京', 9, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '610100', '西安', '西安', 10, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '500000', '重庆', '重庆', 11, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '120000', '天津', '天津', 12, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '320500', '苏州', '苏州', 13, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '330200', '宁波', '宁波', 14, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '350200', '厦门', '厦门', 15, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '350100', '福州', '福州', 16, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '410100', '郑州', '郑州', 17, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '430100', '长沙', '长沙', 18, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '370200', '青岛', '青岛', 19, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '370100', '济南', '济南', 20, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '440600', '佛山', '佛山', 21, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '441900', '东莞', '东莞', 22, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '460100', '海口', '海口', 23, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '530100', '昆明', '昆明', 24, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '210100', '沈阳', '沈阳', 25, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '220100', '长春', '长春', 26, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '230100', '哈尔滨', '哈尔滨', 27, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '340100', '合肥', '合肥', 28, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '360100', '南昌', '南昌', 29, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '450100', '南宁', '南宁', 30, 'normal', NULL),
  ('RESOURCE_REGION_CODES', '520100', '贵阳', '贵阳', 31, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'nationwide', '全国', '全国', 1, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'beijing', '北京', '北京', 2, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'shanghai', '上海', '上海', 3, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'guangzhou', '广州', '广州', 4, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'shenzhen', '深圳', '深圳', 5, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'hangzhou', '杭州', '杭州', 6, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'chengdu', '成都', '成都', 7, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'wuhan', '武汉', '武汉', 8, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'nanjing', '南京', '南京', 9, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'xian', '西安', '西安', 10, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'chongqing', '重庆', '重庆', 11, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'tianjin', '天津', '天津', 12, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'suzhou', '苏州', '苏州', 13, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'ningbo', '宁波', '宁波', 14, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'xiamen', '厦门', '厦门', 15, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'fuzhou', '福州', '福州', 16, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'zhengzhou', '郑州', '郑州', 17, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'changsha', '长沙', '长沙', 18, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'qingdao', '青岛', '青岛', 19, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'jinan', '济南', '济南', 20, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'foshan', '佛山', '佛山', 21, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'dongguan', '东莞', '东莞', 22, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'haikou', '海口', '海口', 23, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'kunming', '昆明', '昆明', 24, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'shenyang', '沈阳', '沈阳', 25, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'changchun', '长春', '长春', 26, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'haerbin', '哈尔滨', '哈尔滨', 27, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'hefei', '合肥', '合肥', 28, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'nanchang', '南昌', '南昌', 29, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'nanning', '南宁', '南宁', 30, 'normal', NULL),
  ('RESOURCE_CITY_NODES', 'guiyang', '贵阳', '贵阳', 31, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'seek_partner', '寻找合伙人', '寻找合伙人', 1, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'resource_swap', '资源互换', '资源互换', 2, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'cross_industry', '异业合作', '异业合作', 3, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'traffic_share', '流量共享', '流量共享', 4, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'project_outsource', '项目外包', '项目外包', 5, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'recruit_anchor', '招募主播', '招募主播', 6, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'channel_cooperation', '渠道合作', '渠道合作', 7, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'brand_exposure', '品牌曝光', '品牌曝光', 8, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'monetization', '商业变现', '商业变现', 9, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'user_growth', '用户增长', '用户增长', 10, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'content_cocreation', '内容共创', '内容共创', 11, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'local_client', '本地获客', '本地获客', 12, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'product_testing', '产品试用', '产品试用', 13, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'joint_live', '联合直播', '联合直播', 14, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'course_collab', '课程合作', '课程合作', 15, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'supply_match', '供应对接', '供应对接', 16, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'investment_match', '投融资对接', '投融资对接', 17, 'normal', NULL),
  ('RESOURCE_WISH_TAGS', 'case_exchange', '案例互换', '案例互换', 18, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'long_term', '长期', '长期', 1, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'short_term', '短期', '短期', 2, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'weekend', '周末', '周末', 3, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'part_time', '兼职', '兼职', 4, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'one_time', '单次结', '单次结', 5, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'remote', '远程', '远程', 6, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'onsite', '到场', '到场', 7, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'urgent', '急单', '急单', 8, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'monthly_package', '月度包', '月度包', 9, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'commission', '佣金制', '佣金制', 10, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'revenue_share', '分成合作', '分成合作', 11, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'fixed_price', '固定报价', '固定报价', 12, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'trial_order', '试单', '试单', 13, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'city_cooperation', '同城合作', '同城合作', 14, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'national_delivery', '全国交付', '全国交付', 15, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'night_slot', '夜间档期', '夜间档期', 16, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'weekday', '工作日', '工作日', 17, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'flexible_schedule', '弹性时间', '弹性时间', 18, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'team_needed', '团队承接', '团队承接', 19, 'normal', NULL),
  ('RESOURCE_NEED_TAGS', 'single_person', '单人可接', '单人可接', 20, 'normal', NULL)
ON DUPLICATE KEY UPDATE
  `dict_label` = VALUES(`dict_label`),
  `dict_value` = VALUES(`dict_value`),
  `dict_sort` = VALUES(`dict_sort`),
  `status` = VALUES(`status`),
  `remark` = VALUES(`remark`);
